flowchart TD
  A(("You have decided to play a game tonight")) --> n8(["Great!!!"])
  ny{{"Are you going to play alone?"}} -- Yes --> nq{{"Singleplayer games"}}
  n8 --> np("Start your computer")
  np --> ny
  n7("Are your friends online?") -- Yes --> nw("Do they wanna play?")
  nq --> nc{{"Time to pick the game"}}
  n7 -- No --> nq
  nw -- No --> nq
  nw -- Yes --> n2("time to pick the game")
  n2 --> n1("World of Warcraft") & n9("StarCraft") & nj("League of legends") & ns("DOTA 2") & nu("Minecraft")
  nc --> ni{{"DOOM"}} & nk{{"Baldurs Gate 3"}} & nb{{"Fallout new vegas"}} & n0{{"Witcher"}} & nl{{"Sims"}}
  nl --> nf[["Now that you have picked a game"]]
  n0 --> nf
  nb --> nf
  nk --> nf
  ni --> nf
  n1 --> no[["Now that you have picked a game"]]
  n9 --> no
  nj --> no
  ns --> no
  nu --> no
  nf --> nd{"Great have fun!"}
  no --> nd
  ny -- No --> n7
  np --> n7
