classDiagram
    class IndianEconomy {
        +String type
        +int globalRankings
        +float GDP
        +float GDPPerCapita
        +getEconomicSectors()
        +getGrowthDrivers()
    }
    
    class EconomicPhases {
        +PreLiberalization 1947-1991
        +PostLiberalization 1991-Present
        +getSectoralChanges()
        +getPolicyShifts()
    }
    
    class PolicyFramework {
        +List regulations
        +List incentives
        +List taxStructure
        +implementPolicy()
        +evaluateOutcomes()
    }
    
    class PublicSector {
        +int numberOfCompanies
        +List strategicIndustries
        +float shareOfGDP
        +getControlMechanisms()
    }
    
    class PrivateSector {
        +int corporatePlayers
        +float marketCapitalization
        +float shareOfGDP
        +getIndustryDistribution()
    }
    
    class TradeProfile {
        +float exportValue
        +float importValue
        +List tradePartners
        +List tradeAgreements
        +getTradeBalance()
    }
    
    class LaborMarket {
        +int workforceSize
        +float laborProductivity
        +float unemploymentRate
        +getChallenges()
    }
    
    class WelfareSystem {
        +float spendingPercentage
        +List programs
        +int beneficiaries
        +compareToGlobalStandards()
    }
    
    class EconomicChallenges {
        +List structuralIssues
        +List inequalityFactors
        +List growthConstraints
        +proposeReforms()
    }
    
    IndianEconomy "1" *-- "2" EconomicPhases
    IndianEconomy "1" *-- "1" PolicyFramework
    IndianEconomy "1" *-- "1" PublicSector
    IndianEconomy "1" *-- "1" PrivateSector
    IndianEconomy "1" *-- "1" TradeProfile
    IndianEconomy "1" *-- "1" LaborMarket
    IndianEconomy "1" *-- "1" WelfareSystem
    IndianEconomy "1" *-- "many" EconomicChallenges
    EconomicPhases --> PolicyFramework