flowchart TD
    A[Requirements Gathering] --> A1[Requirements Analysis]
    A1 --> A2[Requirements Specification]
    A2 --> B[System Design]
    B --> B1[Architecture Design]
    B1 --> B2[Detailed Design]
    B2 --> C[Implementation]

subgraph Planning
A
A1
A2
B
B1
B2
end

subgraph Development
C
end