flowchart TD
    A1[Requirements Analysis]
    A[Requirements]
    B1[Architecture Design]
    B[Design]
    C1[Coding]
    C[Implementation]
    D1[Integration Testing]
    D[Testing]
    subgraph Development
        C
        C1
        D
        D1
    end
    subgraph Planning
        A
        A1
        B
        B1
    end