graph TD

    %% Class Definitions
    classDef timeNode fill:#f9f9f9,stroke:#333,stroke-width:2px,rx:5px,ry:5px
    classDef eicNode fill:#ffdddd,stroke:#cc0000
    classDef crownNode fill:#ddddff,stroke:#0000cc
    classDef indiaNode fill:#ddffdd,stroke:#00cc00
    classDef phaseNode fill:#efefef,stroke:#999999,stroke-width:1px,stroke-dasharray:5 5,rx:10px,ry:10px

    %% Node Definitions
    commercial[Commercial Trading Phase]:::eicNode
    n1600[1600: East India Company Established]:::timeNode