flowchart TD
    A[Requirements Gathering]
    A1
    A2
    B
    B1
    B2
    C
    C1
    C2
    A1 --> A2
    A2 --> B
    B --> B1
    B1 --> B2
    B2 --> C
    C --> C1
    C1 --> C2
    subgraph Planning
        A
        A1
        A2
        B
        B1
        B2
    end
    subgraph Development
        C
        C1
        C2
    end