flowchart TD
    A[Requirements Gathering]
    A1
    A2
    B
    B1
    B2
    C
    A1 --> A2
    A2 --> B
    B --> B1
    B1 --> B2
    B2 --> C
    subgraph Planning
        A
        A1
        A2
        B
        B1
        B2
    end
    subgraph Development
        C
    end